services:
  - postgresql
addons:
  postgresql: "11.3"
env:
  global:
    - PGPORT=5432
before_script:
  - psql -c 'create database plateform_test;' -U postgres
language: ruby
rvm:
  - 2.6.2
script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails spec
